### ISSUE TITLE
About assets

### ISSUE THREAD

**Issue by explosion-mental** [cdown/mack#32]
Hello, what are your thoughts on also ordering assets like **lyrics** (per file) **covers** (per album) maybe artist pics, etc. Are these in line with `mack` or don't matter? What about embedding that info?

I just found out about this tool, always seemed to want something like this and almost started writing something similar (dummy me).

**Comment by cdown** [comment]
Hey! I think realistically mack only intends to handle whatever is embedded in the file.

**Comment by cdown** [comment]
(Closing for now since I don't think anything is going to happen here, but feel free to continue discussion. :-))
